[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
shadowlend_program = "6KiV2x1SxqtPALq9gdyxFXZiuWmwFRdsxMNpnyyPThg3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test]
# Increase startup wait time for large programs (30 seconds)
startup_wait = 30000

[test.validator]
# Bind to all interfaces so Docker containers can access it
url = "http://0.0.0.0:8899"
wss_url = "ws://0.0.0.0:8900"
# Bind RPC to all interfaces and set higher limits for WebSocket connections
bind_address = "0.0.0.0"
rpc_port = 8899
rpc_pubsub_enable_block_subscription = true
# Keep validator running with proper networking settings
[[test.validator.clone]]
address = "https://api.mainnet-beta.solana.com"

[[test.genesis]]
address = "F3G6Q9tRicyznCqcZLydJ6RxkwDSBeHWM458J7V6aeyk"
program = "/home/glitchy_moon/glitchy_moon/github_repo/ShadowLend/shadowlend_program/artifacts/arcium_program_0.5.4.so"
[[test.genesis]]
address = "L2TExMFKdjpN9kozasaurPirfHy9P8sbXoAN1qA3S95"
program = "artifacts/lighthouse.so"

[[test.validator.account]]
address = "EQr6UCd7eyRjpuRsNK6a8WxkgrpSGctKMFuz92FRRh63"
filename = "artifacts/arcium_clock.json"

[[test.validator.account]]
address = "BSC6rWJ9ucqZ6rcM3knfpgdRwCyJ7Q9KsddjeSL4EdHq"
filename = "artifacts/arcium_fee_pool.json"

[[test.validator.account]]
address = "BoVUVSJAhob2cvM5z4JZTdS6VWRSznh3bbzQD1TFjvDP"
filename = "artifacts/arx_mint.json"

[[test.validator.account]]
address = "9AVaR6JcQaX6CJwg5fNivx2qEAQ2nKAn86DRi7vL5kK2"
filename = "artifacts/wallet_acc_9AVa_5kK2.json"

[[test.validator.account]]
address = "5hAvtE7yzxjtSqnLnAuUAV4W3so472SAmFtWzDPVe5zi"
filename = "artifacts/arx_ata_9AVa_5kK2.json"

[[test.validator.account]]
address = "5Bg5Nudnj1GufVoKu3Sq6o4jr3WkdbvproSgYvtWXbnT"
filename = "artifacts/wallet_acc_5Bg5_XbnT.json"

[[test.validator.account]]
address = "5FMyCSA4mFeus49BE2qzsXiwxb1ZoUGkoqSM9xz6be9i"
filename = "artifacts/wallet_acc_callback_5FMy_be9i.json"

[[test.validator.account]]
address = "GyJcqYRYH1ZMVA4uuz6e9HH7qCzCB79D4PkN3W6uMmje"
filename = "artifacts/arx_ata_5Bg5_XbnT.json"

[[test.validator.account]]
address = "7H2pfwgYDweV6cVUiUEfabiN7YYRpgekRQwoEvkREwED"
filename = "artifacts/operator_acc_5Bg5_XbnT.json"

[[test.validator.account]]
address = "9CaJVqHPWPGRDY1x7Eew5a3BuTcCYm8JQXmk8coE1Zkf"
filename = "artifacts/arx_node_5Bg5_XbnT.json"

[[test.validator.account]]
address = "93TBiGar5NX8WrTYWNpkLGnnmu1uJxifvPzzmzYXWuhu"
filename = "artifacts/wallet_acc_93TB_Wuhu.json"

[[test.validator.account]]
address = "tsyNGB1ebYTVeNNbjB1JiR4Z4nU9bAW7byssFFcVFGg"
filename = "artifacts/wallet_acc_callback_tsyN_VFGg.json"

[[test.validator.account]]
address = "ypctFL2A62fnnAZSmLh22nRZEVrMd2xWazX9pT8zHDa"
filename = "artifacts/arx_ata_93TB_Wuhu.json"

[[test.validator.account]]
address = "FQFDpoum1NxW9uJUES1PpAGntSj9gNBmbFk7mDR5VCVj"
filename = "artifacts/operator_acc_93TB_Wuhu.json"

[[test.validator.account]]
address = "HwMdVdMkep2njXpEVZmWrbYPtsGdpJJvZzSb673YMZBy"
filename = "artifacts/arx_node_93TB_Wuhu.json"

[[test.validator.account]]
address = "3kMQur1kfAYp5JeoXRq11CUnP5x8DT5dw12rHnfoJNPg"
filename = "artifacts/cluster_acc_0.json"

[[test.validator.account]]
address = "4XZZYQXw7hZK9UNXeXJgzjW8E9ud9LuGSnpPpuRt9JkZ"
filename = "artifacts/compute_confidential_repay_raw_circuit_0.json"

[[test.validator.account]]
address = "3czntWPjLiS1NK4W42PsuPRdCyNqqph3hqmRgA8UUPbA"
filename = "artifacts/compute_confidential_deposit_raw_circuit_0.json"

[[test.validator.account]]
address = "AGySsGKuhY3wkyggKLjYer71t86ydhGpnzC5YTqqxN4U"
filename = "artifacts/compute_confidential_liquidate_raw_circuit_0.json"

[[test.validator.account]]
address = "DYQdieGuqWdPNGTjBBPqNYibRUz7g443vusbPN74Zmgx"
filename = "artifacts/compute_confidential_liquidate_raw_circuit_1.json"

[[test.validator.account]]
address = "Ba2T7AiqvyUa3FoGgWnN3mDJaTNuQCi4Q32BTUMeMiuV"
filename = "artifacts/compute_confidential_borrow_raw_circuit_0.json"

[[test.validator.account]]
address = "5skD4fsYYZrWS5qSZq54QiYKQtSyQKNbiswMH683Dqc4"
filename = "artifacts/compute_confidential_withdraw_raw_circuit_0.json"

[[test.validator.account]]
address = "8CdWf2JLNVZT6gWKUcsxBET9qfLg4yLaJYKoiYGcPJhX"
filename = "artifacts/compute_confidential_interest_raw_circuit_0.json"

[[test.validator.account]]
address = "BxNCthjyCsbc12YBVHMBrN7N4p9P2o2bWai5HPTzXrkV"
filename = "artifacts/mxe_keygen_comp_def.json"

[[test.validator.account]]
address = "GYVtZfNjSN3rH7xeTkhToFUeVAJFij8PazbYpcUgKdri"
filename = "artifacts/mxe_keygen_comp.json"

[[test.validator.account]]
address = "BDW722MXptNvUThYZo6WizZFdp1Btc4eJ44nFf55Zbtt"
filename = "artifacts/mxe_acc.json"

[[test.validator.account]]
address = "RJ56J5zMy5yXFYcWHjcQfdT2f2PQAGMom7UMyHw3kkj"
filename = "artifacts/mempool_acc.json"

[[test.validator.account]]
address = "8dZouGFqvrkVS6wgzwynwvQNvnHqPdyi8Eq1Zm6z4KSi"
filename = "artifacts/executing_pool_acc.json"
