[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
shadowlend_program = "J6hwZmTBYjDQdVdbeX7vuhpwpqgrhHUqQaUk8qYsZvXK"

[programs.localnet]
shadowlend_program = "AQMgx9c9vL1SCnZE7E4r4HRFZpHZDUcZJfdKt5YULRjD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test]
startup_wait = 30000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "F3G6Q9tRicyznCqcZLydJ6RxkwDSBeHWM458J7V6aeyk"
program = "/home/glitchy_moon/glitchy_moon/github_repo/ShadowLend/shadowlend_program/artifacts/arcium_program_0.5.4.so"

[[test.genesis]]
address = "L2TExMFKdjpN9kozasaurPirfHy9P8sbXoAN1qA3S95"
program = "artifacts/lighthouse.so"

[test.validator]
bind_address = "0.0.0.0"
url = "http://0.0.0.0:8899"
ledger = ".anchor/test-ledger"
rpc_port = 8899
